<location>
    <unit-number><![CDATA[{$location->getUnitNumber()}]]></unit-number>
    <street-address><![CDATA[{$location->getStreetAddress()}]]></street-address>
    <display-address>{if $location->getDisplayAddress()}yes{else}no{/if}</display-address>
    <city-name><![CDATA[{$location->getCityName()}]]></city-name>
    <zipcode>{$location->getZipcode()}</zipcode>
    <county><![CDATA[{$location->getCounty()}]]></county>
    <state-code>{$location->getStateCode()}</state-code>
    <street-intersection><![CDATA[{$location->getStreetIntersection()}]]></street-intersection>
    <parcel-id><![CDATA[{$location->getParcelId()}]]></parcel-id>
    <building-name><![CDATA[{$location->getBuildingName()}]]></building-name>
    <subdivision><![CDATA[{$location->getSubdivision()}]]></subdivision>
    <neighborhood-name><![CDATA[{$location->getNeighborhoodName()}]]></neighborhood-name>
    <neighborhood-description><![CDATA[{$location->getNeighborhoodDescription()}]]></neighborhood-description>
    <elevation>{$location->getElevation()|string_format:"%d"}</elevation>
    <longitude>{$location->getLongitude()}</longitude>
    <latitude>{$location->getLatitude()}</latitude>
    <geocode-type>{$location->getGeocodeType()}</geocode-type>
    <directions><![CDATA[{$location->getDirections()}]]></directions>
</location>